require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

inhibit_all_warnings!
platform :ios, '10.0'

target 'czzapp' do
    config = use_native_modules!
    use_react_native!(
        :path => config["reactNativePath"]
    )

    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    post_install do |installer|
        flipper_post_install(installer)
    end
end
