export const Login_Identity = 'Login_Identity'
export const Login_Account = 'Login_Account'
export const Login_Password = 'Login_Password'
export const Login_Token = 'Login_Token'
export const Log_Out = 'Log_Out'
export const greenColor = '#54D693'
export const gradienRightGreenColor = '#83E3AE'
export const gradienViewRightGreenColor = '#5BE7AA'
